// Generated by CoffeeScript 1.8.0
(function() {
  var JobStatus, Nag, config, moment;

  config = require('cloud/config');

  Nag = require('cloud/models/nag');

  JobStatus = require('cloud/models/job_status');

  moment = require('cloud/lib/moment-timezone-with-data');

  exports.initialize = function() {
    return Parse.Cloud.job("send_nags", function(request, status) {
      var nags_sent, now;
      nags_sent = 0;
      now = new Date();
      return JobStatus.findOrCreate().then(function(job_status) {
        var current_time, day, last_run;
        day = moment(new Date()).tz("America/New_York").format('ddd').toUpperCase();
        last_run = parseInt(moment(job_status.get('last_run_at')).tz("America/New_York").format('HHmm'));
        current_time = parseInt(moment(new Date()).tz("America/New_York").format('HHmm'));
        console.log("TIME: " + current_time);
        console.log("DAY: " + day);
        return Nag.findAllEach({
          containsAll: {
            days: [day]
          },
          greaterThan: {
            time: last_run
          },
          lessThanOrEqualTo: {
            time: current_time
          }
        }).each(function(nag) {
          nag.notify();
          return nags_sent++;
        }).then(function() {
          job_status.set('last_run_at', now);
          return job_status.save();
        }).then(function() {
          return status.success("Sent " + nags_sent + " nags");
        }, function(err) {
          return status.error(err);
        });
      });
    });
  };

}).call(this);
