// Generated by CoffeeScript 1.8.0
(function() {
  var JobStatus, ParseFinder;

  ParseFinder = require('cloud/mixins/finder');

  module.exports = JobStatus = ParseFinder.extend("JobStatus", {
    foo: 'bar'
  }, {
    findOrCreate: function() {
      return this.findBy({}).then((function(_this) {
        return function(status) {
          if (status == null) {
            status = new _this({
              last_run_at: new Date()
            });
          }
          return status.save();
        };
      })(this));
    }
  });

}).call(this);
