// Generated by CoffeeScript 1.8.0
(function() {
  var Nag, ParseFinder;

  ParseFinder = require('cloud/mixins/finder');

  module.exports = Nag = ParseFinder.extend("Nag", {
    foo: 'bar'
  });

}).call(this);
