// Generated by CoffeeScript 1.8.0
(function() {
  exports.$ = {
    ajax: function(options, splitParams) {
      var data, method, oldparams, url, _ref, _ref1;
      if (options == null) {
        options = {};
      }
      if (splitParams == null) {
        splitParams = true;
      }
      if (splitParams) {
        _ref = options.url.split("?"), url = _ref[0], oldparams = _ref[1];
      } else {
        url = options.url;
      }
      method = (_ref1 = options.method) != null ? _ref1 : "GET";
      data = {
        method: method,
        body: options.params,
        url: url,
        headers: {
          'Content-Type': 'application/json'
        },
        success: function(data) {
          if (options.dataType === 'json') {
            data.text = JSON.parse(data.text);
          }
          if (options.success != null) {
            return options.success(data.text);
          }
        },
        error: function(data) {
          if (options.error != null) {
            options.error(data);
          }
          return console.error('Request failed with response code ' + data.status);
        }
      };
      if (splitParams) {
        data.params = options.params;
      }
      return Parse.Cloud.httpRequest(data);
    }
  };

}).call(this);
